title: Faizan Darwesh
url: "https://faizandarwesh.github.io/"
baseurl: ""
repository: https://faizandarwesh.github.io/
markdown: kramdown

tracking_id: #

sass:
    style: compressed
    sass_dir: _sass
